export const FETCH_DATA_REQUEST = 'DEPOSIT_FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'DEPOSIT_FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'DEPOSIT_FETCH_DATA_ERROR'
export const FETCH_DATA_SETTINGS_REQUEST = 'FETCH_DATA_SETTINGS_REQUEST'
export const FETCH_DATA_SETTINGS_SUCCESS = 'FETCH_DATA_SETTINGS_SUCCESS'
export const DEPOSIT_DATA_REQUEST = 'DEPOSIT_DATA_REQUEST'
export const DEPOSIT_DATA_SUCCESS = 'DEPOSIT_DATA_SUCCESS'
export const DEPOSIT_DATA_ERROR = 'DEPOSIT_DATA_ERROR'
export const DEPOSIT_PENDING_ACTION = 'DEPOSIT_PENDING_ACTION'

export const ITEM_CHANGE = 'ITEM_CHANGE'
export const CARDTYPE_CHANGE = 'CARDTYPE_CHANGE'

export const SET_MODAL = 'SET_MODAL'
export const SET_MODAL_SUCCESS = 'SET_MODAL_SUCCESS'
export const SET_MODAL_FAILURE = 'SET_MODAL_FAILURE'

export const SET_LOADING = 'SET_LOADING'
export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS'
export const SET_LOADING_FAILURE = 'SET_LOADING_FAILURE'

export const SEND_NOTIFICATION_START = 'SEND_NOTIFICATION_START'
export const SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS'
export const SEND_NOTIFICATION_ERROR = 'SEND_NOTIFICATION_ERROR'
