//  Crud
export const FETCH_DATA_REQUEST = 'DEPOSIT_FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'DEPOSIT_FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'DEPOSIT_FETCH_DATA_ERROR'
export const ITEM_CHANGE = 'DEPOSIT_ITEM_CHANGE'
