export const FETCH_GENERAL_SETTINGS_SUCCESS = 'FETCH_GENERAL_SETTINGS_SUCCESS'
export const REQUEST_GENERAL_SETTINGS_FAILURE = 'REQUEST_GENERAL_SETTINGS_FAILURE'
export const FETCH_GENERAL_SETTINGS = 'FETCH_GENERAL_SETTINGS'

export const SET_COMMON_COUNTRY = 'SET_COMMON_COUNTRY'
export const SET_METHOD = 'SET_METHOD'

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS'
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE'

export const FETCH_NEW_ACCOUNT = 'FETCH_NEW_ACCOUNT'
export const FETCH_NEW_ACCOUNT_SUCCESS = 'FETCH_NEW_ACCOUNT_SUCCESS'
export const FETCH_NEW_ACCOUNT_FAILURE = 'FETCH_NEW_ACCOUNT_FAILURE'

export const FETCH_PAGO_COUNTRIES = 'FETCH_PAGO_COUNTRIES'
export const FETCH_PAGO_COUNTRIES_SUCCESS = 'FETCH_PAGO_COUNTRIES_SUCCESS'
export const FETCH_PAGO_COUNTRIES_FAILURE = 'FETCH_PAGO_COUNTRIES_FAILURE'

export const NEW_DEPOSIT = 'NEW_DEPOSIT'
export const NEW_DEPOSIT_SUCCESS = 'NEW_DEPOSIT_SUCCESS'
export const NEW_DEPOSIT_FAILURE = 'NEW_DEPOSIT_FAILURE'

export const COMMON_SCHEMA_REQUEST = 'COMMON_SCHEMA_REQUEST'
export const COMMON_SCHEMA_SUCCESS = 'COMMON_SCHEMA_SUCCESS'
export const COMMON_SCHEMA_FAILURE = 'COMMON_SCHEMA_FAILURE'

export const SET_COMMON_RESPONSE = 'SET_COMMON_RESPONSE'

export const KEY = 'common'

export const consts = {
  REQUEST_GENERAL_SETTINGS_FAILURE,
  FETCH_GENERAL_SETTINGS,
  FETCH_GENERAL_SETTINGS_SUCCESS,
  SET_COMMON_COUNTRY,
  SET_METHOD,
  FETCH_COUNTRIES,
  FETCH_COUNTRIES_SUCCESS,
  FETCH_COUNTRIES_FAILURE,
  FETCH_NEW_ACCOUNT,
  FETCH_NEW_ACCOUNT_SUCCESS,
  FETCH_NEW_ACCOUNT_FAILURE,
  NEW_DEPOSIT,
  NEW_DEPOSIT_SUCCESS,
  NEW_DEPOSIT_FAILURE,
  SET_COMMON_RESPONSE,
  COMMON_SCHEMA_REQUEST,
  COMMON_SCHEMA_SUCCESS,
  COMMON_SCHEMA_FAILURE,
  KEY,
}

export default consts
