const initial = {
  fetching: false,
  response: {},
  lang: {
    mz_cashier_bitcoin_tab_title: 'Bitcoin',
    mz_cashier_coupon_title: 'Discount Coupon',
    mz_cashier_coupon_not_valid: 'The coupon is not valid',
    mz_cashier_coupon_placeholder: 'Input discount coupon',
    mz_cashier_cc_deposit_form: 'Credit Card',
    mz_cashier_amount_title: 'Amount',
    mz_cashier_other_amount: 'Other Amount',
    mz_cashier_card_info_title: 'Card Information',
    mz_cashier_card_num: 'Credit Card Number',
    mz_cashier_card_type: 'Card Type',
    mz_cashier_exp_month: 'Expiration  Date',
    mz_cashier_month: 'Month',
    mz_cashier_year: 'Year',
    mz_cashier_cc_holder_title: 'Credit Card Holder Info',
    mz_cashier_country_combo: 'Country',
    mz_cashier_first_name: 'First Name',
    mz_cashier_last_name: 'Last Name',
    mz_cashier_address: 'Address',
    mz_cashier_city: 'City',
    mz_cashier_email: 'Email',
    mz_cashier_postcode: 'Postal Code',
    mz_cashier_phone: 'Phone',
    mz_cashier_submit: 'Deposit',
    mz_cashier_deposit_failed: 'Something went wrong',
    mz_cashier_deposit_failed2: 'Deposit Failed',
    mz_cashier_existing_cards: 'Existing Cards',
    mz_cashier_select_existing_cards: 'Select Existing Card',
    mz_cashier_select_mode: 'Select Mode',
    mz_cashier_new_card: 'New Card',
    mz_cashier_loading: 'Loading',
    mz_cashier_force_new_cc:
      'Dear Customer,As an additional security level, your transaction will be processed using 3D secure measure. Please complete as described in the following page',
    mz_cashier_apm_tab_title: 'E-Wallet',
    mz_cashier_lpm_tab_title: 'Local Payment Method',
    mz_cashier_apm_choose_title: 'Payment Method (Choose one)',
    mz_cashier_customer_info: 'Customer Info',
    mz_cashier_apm_account: 'APM Account',
    mz_cashier_validation_cc: 'Credit Card Number is Required',
    mz_cashier_validation_cc2: 'Invalid CC Type or Number',
    mz_cashier_validation_cvv: 'CVV is Required',
    mz_cashier_validation_expiration: 'Expiration date has Passed',
    mz_cashier_validation_country: 'Country is Required',
    mz_cashier_validation_country2: 'Service unavailable in your area',
    mz_cashier_validation_name: 'Name is Required',
    mz_cashier_validation_name2: 'At least 3 letters',
    mz_cashier_validation_address: 'Address is Required',
    mz_cashier_validation_address2: 'At least 5 characters',
    mz_cashier_validation_city: 'City is Required',
    mz_cashier_validation_city2: 'At least 3 characters',
    mz_cashier_validation_post: 'Postal Code is Required',
    mz_cashier_validation_post2: 'At least 2 characters',
    mz_cashier_validation_phone: 'Phone is Required',
    mz_cashier_validation_phone2: 'At least 8 digits',
    mz_cashier_not_valid_credit_card:
      'This is not a valid Credit Card.  Please check your CARD TYPE and NUMBER and try again.',
    mz_cashier_not_valid_credit_card_type: 'Card type not supported',
    mz_cashier_ssl_tooltip: 'This is a secure 256-bit SSL Encrypted payment. You are safe',
    mz_cashier_cvv_tooltip: 'The last 3 digits displayed on the back of your card',
    mz_cashier_max_amount_tooltip: 'This is the maximum amount for a single deposit',
    mz_cashier_min_amount_tooltip: 'This is the minimum amount for a single deposit',
    mz_cashier_footer_disclaimer:
      'Payments are being processed by Titan Trade<br>Phone: +44 2036088333<br><br>Some credit cards require 3D verification.<br>In such case, contact your bank for receving the verification code',
    mz_cashier_ok: 'OK',
    mz_cashier_not_valid_exp_date: 'Expiration date has Passed',
    mz_cashier_choose_account: 'Account Number',
    mz_cashier_wire_tab_title: 'Wire Transfer',
    mz_cashier_wire_account_details: 'Account Details',
    mz_cashier_wire_details_description:
      'Please deposit to the following bank account details.<br>Once funds are received, it will be credited to your trading account.',
    mz_cashier_netteler_email: 'Account ID or E-mail Address',
    mz_cashier_netteler_id: 'Secure ID or Authentication Code',
    mz_cashier_popup_accountType_title: 'Complete your choice',
    mz_cashier_popup_accountType_body:
      'Deposit {amount}{currency} or more and one of our representatives will contact you to grand you your benefits',
    mz_cashier_popup_3d_verification:
      'Please note that all deposits above 1,000 USD will go through 3D Secure verification, which is an additional security layer for online credit and debit card transactions designed to protect cardholders and prevent fraudulent transactions. You will be asked to input either a one-time password being sent to your mobile phone or email, or a fixed password that had been provided to you in the past by your issuing bank',
    mz_cashier_popup_blocked_ip: 'Deposit is not allowed from your country',
    mz_cashier_choose_bank: 'Select Bank',
    mz_cashier_pid: 'Personal ID',
    mz_cashier_lang: 'EN',
  },
  method: 'creditCard',
  countries: {},
  country_phone_prefix: {},
  country_by_ip: 'AF',
  selectedCountry: 'AF',
}

export default initial
