//  Quotes
export const REQUEST_QUOTES_START = 'REQUEST_QUOTES_START'
export const REQUEST_QUOTES_ARRAY_START = 'REQUEST_QUOTES_ARRAY_START'
export const REQUEST_QUOTES_END = 'REQUEST_QUOTES_END'
export const RECEIVE_QUOTES_FULFILLED = 'RECEIVE_QUOTES_FULFILLED'
export const REQUEST_QUOTES_FAILED = 'REQUEST_USER_REPOS_FAILED'

export const MAKE_ORDER_START = 'MAKE_ORDER_START'
export const MAKE_ORDER_FULFILLED = 'MAKE_ORDER_FULFILLED'
export const MAKE_ORDER_FAILURE = 'MAKE_ORDER_FAILURE'

export const REQUEST_TERMS_START = 'REQUEST_TERMS_START'
export const REQUEST_TERMS_FULFILLED = 'REQUEST_TERMS_FULFILLED'
export const REQUEST_TERMS_FAILURE = 'REQUEST_TERMS_FAILURE'

export const VERIFICATE_PHONE_START = 'VERIFICATE_PHONE_START'
export const VERIFICATE_PHONE_FULFILLED = 'VERIFICATE_PHONE_FULFILLED'
export const VERIFICATE_PHONE_FAILURE = 'VERIFICATE_PHONE_FAILURE'

export const VERIFICATE_CODE_START = 'VERIFICATE_CODE_START'
export const VERIFICATE_CODE_FULFILLED = 'VERIFICATE_CODE_FULFILLED'
export const VERIFICATE_CODE_FAILURE = 'VERIFICATE_CODE_FAILURE'
