//  Quotes
export const REQUEST_QUOTES_START = 'REQUEST_QUOTES_START'
export const RECEIVE_QUOTES_SUCCESS = 'RECEIVE_QUOTES_SUCCESS'
export const RECEIVE_QUOTES_FAILED = 'RECEIVE_QUOTES_FAILED'

export const CHOOSE_SELL_OPERATION = 'CHOOSE_SELL_OPERATION'
export const CHOOSE_BUY_OPERATION = 'CHOOSE_BUY_OPERATION'
