//  Quotes
export const REQUEST_QUOTES_START = 'REQUEST_QUOTES_START'
export const REQUEST_QUOTES_ARRAY_START = 'REQUEST_QUOTES_ARRAY_START'
export const REQUEST_QUOTES_END = 'REQUEST_QUOTES_END'
export const RECEIVE_QUOTES_FULFILLED = 'RECEIVE_QUOTES_FULFILLED'
export const REQUEST_QUOTES_FAILED = 'REQUEST_USER_REPOS_FAILED'

export const MAKE_ORDER_START = 'MAKE_ORDER_START'
export const MAKE_ORDER_FULFILLED = 'MAKE_ORDER_FULFILLED'
export const MAKE_ORDER_FAILURE = 'MAKE_ORDER_FAILURE'
