version: '3'

services:
  frontend:
    image: univerio/cra-backend:latest
    container_name: frontend
    domainname: cra.xyz
    hostname: frontend
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - UI_BACKEND=127.0.0.1:4060
      - DEBUG=app:*
      - NODE_ENV=production
    ports:
      - 3000:3000
