// Request User repos
export const USER_SET = 'USER_SET'
export const LOGIN_SET = 'LOGIN_SET'

export const REQUEST_USERS_START = 'REQUEST_USERS_START'
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS'
export const REQUEST_USERS_FAILED = 'REQUEST_USERS_FAILED'

export const REQUEST_USER_REPOS_START = 'REQUEST_USER_REPOS_START'
export const REQUEST_USER_REPOS_SUCCESS = 'REQUEST_USER_REPOS_SUCCESS'
export const REQUEST_USER_REPOS_FAILED = 'REQUEST_USER_REPOS_FAILED'
