export const FETCH_GENERAL_SETTINGS_SUCCESS = 'FETCH_GENERAL_SETTINGS_SUCCESS'
export const REQUEST_GENERAL_SETTINGS_FAILURE = 'REQUEST_GENERAL_SETTINGS_FAILURE'
export const FETCH_GENERAL_SETTINGS = 'FETCH_GENERAL_SETTINGS'

export const SET_DEPOSIT_DATA = 'SET_DEPOSIT_DATA'
export const SET_COMMON_AMOUNT = 'SET_COMMON_AMOUNT'
export const SET_COMMON_COUNTRY = 'SET_COMMON_COUNTRY'
export const SET_PAGO_COUNTRY = 'SET_PAGO_COUNTRY'

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS'
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE'

export const FETCH_NEW_ACCOUNT = 'FETCH_NEW_ACCOUNT'
export const FETCH_NEW_ACCOUNT_SUCCESS = 'FETCH_NEW_ACCOUNT_SUCCESS'
export const FETCH_NEW_ACCOUNT_FAILURE = 'FETCH_NEW_ACCOUNT_FAILURE'

export const FETCH_PAGO_COUNTRIES = 'FETCH_PAGO_COUNTRIES'
export const FETCH_PAGO_COUNTRIES_SUCCESS = 'FETCH_PAGO_COUNTRIES_SUCCESS'
export const FETCH_PAGO_COUNTRIES_FAILURE = 'FETCH_PAGO_COUNTRIES_FAILURE'

export const FETCH_EXISTING_CARDS = 'FETCH_EXISTING_CARDS'
export const FETCH_EXISTING_CARDS_SUCCESS = 'FETCH_EXISTING_CARDS_SUCCESS'
export const FETCH_EXISTING_CARDS_FAILURE = 'FETCH_EXISTING_CARDS_FAILURE'

export const NEW_DEPOSIT = 'NEW_DEPOSIT'
export const NEW_DEPOSIT_SUCCESS = 'NEW_DEPOSIT_SUCCESS'
export const NEW_DEPOSIT_FAILURE = 'NEW_DEPOSIT_FAILURE'

export const DDD_URL_VARIFICATION = 'DDD_URL_VARIFICATION'
export const DDD_URL_VARIFICATION_SUCCESS = 'DDD_URL_VARIFICATION_SUCCESS'
export const DDD_URL_VARIFICATION_FAILURE = 'DDD_URL_VARIFICATION_FAILURE'

export const SET_LOADING = 'SET_LOADING'
export const SET_LOADING_SUCCESS = 'SET_LOADING_SUCCESS'
export const SET_LOADING_FAILURE = 'SET_LOADING_FAILURE'

export const SET_MODAL = 'SET_MODAL'
export const SET_MODAL_SUCCESS = 'SET_MODAL_SUCCESS'
export const SET_MODAL_FAILURE = 'SET_MODAL_FAILURE'

export const KEY = 'common'

export const consts = {
  REQUEST_GENERAL_SETTINGS_FAILURE,
  FETCH_GENERAL_SETTINGS,
  FETCH_GENERAL_SETTINGS_SUCCESS,
  SET_DEPOSIT_DATA,
  SET_COMMON_AMOUNT,
  SET_COMMON_COUNTRY,
  SET_PAGO_COUNTRY,
  SET_LOADING,
  SET_LOADING_SUCCESS,
  SET_LOADING_FAILURE,
  FETCH_COUNTRIES,
  FETCH_COUNTRIES_SUCCESS,
  FETCH_COUNTRIES_FAILURE,
  FETCH_PAGO_COUNTRIES,
  FETCH_PAGO_COUNTRIES_SUCCESS,
  FETCH_PAGO_COUNTRIES_FAILURE,
  FETCH_NEW_ACCOUNT,
  FETCH_NEW_ACCOUNT_SUCCESS,
  FETCH_NEW_ACCOUNT_FAILURE,
  SET_MODAL,
  SET_MODAL_SUCCESS,
  SET_MODAL_FAILURE,
  FETCH_EXISTING_CARDS,
  FETCH_EXISTING_CARDS_SUCCESS,
  FETCH_EXISTING_CARDS_FAILURE,
  NEW_DEPOSIT,
  NEW_DEPOSIT_SUCCESS,
  NEW_DEPOSIT_FAILURE,
  DDD_URL_VARIFICATION,
  DDD_URL_VARIFICATION_SUCCESS,
  DDD_URL_VARIFICATION_FAILURE,
  KEY,
}

export default consts
